### ISSUE TITLE
Links doesn't work good on Android

### ISSUE THREAD

**Issue by Sandstedt** [mojs/mojs-website#15]
When a Android user clicks an link in Chrome (using react component react-tappable (used in UniteLink) ), this error occurs:

`Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.`

Works when long clicking a link, not on a single tap. Eg only works after the underline animation is complete.

I guess there's a timeout wating for the animation to complete before sending the user to the URL.

**Comment by legomushroom** [comment]
@Sandstedt you think it awaits for CSS transition to complete, before proceeding to the link? that's weird behavior

**Comment by Sandstedt** [comment]
Not sure, but some timer related stuff anyway [according to Google](crbug.com/574343). Same problem on their demo site: http://jedwatson.github.io/react-tappable/. Maybe just use a simple <a> with a span inside for the hover animation?

**Comment by legomushroom** [comment]
@Sandstedt probably `react-tappable`'s issue, if they have it on their site?

**Comment by Sandstedt** [comment]
Yeah exactly. And it hasn't been developed for a while. Seems quite dead. Was there a reason youre using that instead of a regular link?

**Comment by legomushroom** [comment]
@Sandstedt any updates on this?

**Comment by Sandstedt** [comment]
Nope. I guess the easiest is just to rip out the tapable plugin and run with native links?

**Comment by Sandstedt** [comment]
Ah, it seems they fixed it now. So just updated tapable to the latest version.

**Comment by indolering** [comment]
This isn't working on mobile Firefox.
